POST http://172.20.117.210:5000/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=WebAppBoundary


--WebAppBoundary
Content-Disposition: form-data; name="session_id"
Content-Type: text/plain

session-29
--WebAppBoundary
Content-Disposition: form-data; name="party_id"
Content-Type: text/plain

party_id_1
--WebAppBoundary
Content-Disposition: form-data; name="epoch"
Content-Type: text/plain

2
--WebAppBoundary
Content-Disposition: form-data; name="local_model"
Content-Type: text/plain

1
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test.pth.tar"
Content-Type: text/plain

< test.pth.tar
--WebAppBoundary--

###

POST http://127.0.0.1:5000/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=WebAppBoundary


--WebAppBoundary
Content-Disposition: form-data; name="session_id"
Content-Type: text/plain

session-18
--WebAppBoundary
Content-Disposition: form-data; name="party_id"
Content-Type: text/plain

party_id_1234
--WebAppBoundary
Content-Disposition: form-data; name="local_model"
Content-Type: text/plain

1
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test.txt"
Content-Type: text/plain

< test.txt
--WebAppBoundary--


### Start Docker Container
POST http://localhost:5000/start-container
Content-Type: application/json

{
    "image": "test-docker"
}

###

### Get Shapley Value
GET http://localhost:5000/get-shapley-values?session_id=session-5

###

### Using Shapley2 Server
POST http://gpuserver:5000/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=WebAppBoundary


--WebAppBoundary
Content-Disposition: form-data; name="session_id"
Content-Type: text/plain

session-22
--WebAppBoundary
Content-Disposition: form-data; name="party_id"
Content-Type: text/plain

party_id_2234
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test.txt"
Content-Type: text/plain

< test.txt
--WebAppBoundary--

###
### Get Shapley Value
GET http://127.0.0.1:5000/get-shapley-values?session_id=session-28

###
### Get Shapley Value
GET http://127.0.0.1:5000/get-shapley-values-mock?session_id=session-1

###
### Initiate Session
POST http://172.20.117.210:5000/initiate-session HTTP/1.1
Content-Type: application/json

{
    "session_id": "session-29",
    "party_id": ["party_id_1", "party_id_2", "party_id_3"]
}








