POST http://127.0.0.1:5000/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=WebAppBoundary


--WebAppBoundary
Content-Disposition: form-data; name="session_id"
Content-Type: text/plain

session_id_1234
--WebAppBoundary
Content-Disposition: form-data; name="party_id"
Content-Type: text/plain

party_id_1234

--WebAppBoundary
Content-Disposition: form-data; name="epoch"
Content-Type: text/plain

1
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test.txt"
Content-Type: text/plain

< test.txt
--WebAppBoundary--
```







