POST http://127.0.0.1:5000/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=WebAppBoundary


--WebAppBoundary
Content-Disposition: form-data; name="session_id"
Content-Type: text/plain

session-11
--WebAppBoundary
Content-Disposition: form-data; name="party_id"
Content-Type: text/plain

party_id_1234

--WebAppBoundary
Content-Disposition: form-data; name="epoch"
Content-Type: text/plain

10
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test.txt"
Content-Type: text/plain

< test.txt
--WebAppBoundary--

###

### Start Docker Container
POST http://localhost:5000/start-container
Content-Type: application/json

{
    "image": "test-docker"
}

###

### Get Shapley Value
GET http://localhost:5000/get-shapley-values?session_id=session-5








